apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ayberkdd/auth
          env:
          - name : MONGO_URI
            value: mongodb://auth-mongo-srv:27017/auth
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwtsecret
                key: JWT_SECRET
                optional: false # same as default; "mysecret" must exist
                                # and include a key named "username"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
